#+TITLE:Implementing Modal with ed, in ed

This project is a proof of concept for compilation of Modal
(a string-rewriting system, as explained by [[https://wryl.tech/projects/modal.html][wryl]] and [[https://wiki.xxiivv.com/site/modal.html][Devine Lu Linvega]]) into ed scripts.
Using ed script as a compiler!
All based on regex substitution (using POSIX BREs) and churning out repetitive patterns.

* Getting started

Clone the repository:
#+begin_src sh
  git clone https://github.com/aartaka/modal.ed
#+end_src
and then use the bundled [[./build.sh]] to compile any given Modal file:
#+begin_src sh
  ./build.sh /path/to/file.modal
#+end_src
Save the output script to a file
#+begin_src sh
  ./build.sh /path/to/file.modal > file.ed
#+end_src
and run it with ed:
#+begin_src sh
  ed -s input-file.txt < file.ed
#+end_src

This ed script /should/ do the same thing as Modal.
Theoretically.
Right now, the behavior is that of [[https://www.sheeeeeeeep.art/types-of-modal.html#static-modal][Static Modal]], though the plan is to get a couple of levels higher.

* Limitations
- It compiles to static ed substitution rules, thus it has no dynamicity and homoiconicity.
  - [ ] Homoiconicity can probably be achieved by re-evaluating a script on itself in some way, but I didn't try that yet.
- [ ] No I/O.
- [ ] No lambda support.
- No Thuesday extensions like ALU and drawing. And it's unlikely to ever be implemented—I don't like the idea of expanding pure systems with "practical" features. But I'll be glas to accept a contribution if someone steps up!

* The Story
I joined Merveilles Town in August 2024, after my previous Fediverse home, kopimi.space, shut down.
I found a lot of cool folks on Merveilles, doing all sorts of crazy projects.
And I value that!

One project that everyone was hyped up about was Modal—a simple yet powerful programming system/paradigm.
As someone having a taste of rewriting systems... in ed... I was interested.
So I asked the most sensible question: why Modal and not ed/sed?

Even though I've got sensible replies then, I was uneasy—why use Modal if ed works well enough?
Thus this project—an attempt to fit Modal into ed rules.
This is a doomed enterprise, but at least it's fun!
